name = 'Simple Wiki'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'A theme for a wiki website'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['keywords']
# features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'Jian Wei Tay', homepage = 'https://jianweitay.com'},
]